import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
live_config_reload = true

[font]
size = 20.0

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.80
blur = true

[window.padding]
x = 18
y = 16

